### ISSUE TITLE
Plugin prevents comment highlighting with Clojure files

### ISSUE THREAD

**Issue by lpil** [oblitum/rainbow#11]
Without
![Without](http://i.imgur.com/8SdwuZi.png)

With
![With](http://i.imgur.com/6TFYdeP.png)

**Comment by actionless** [comment]
so i did not understood how it works, symbols listed as operators would be ignored or treated as pair symbols instead?

like in case of lua, there both comments became unhighlighted:
```lua
-- comment
```
```lua
--[[
comment
--]]
```

what should i add as "custom operators" for such case?
