### ISSUE TITLE
Coloring is mixed up

### ISSUE THREAD

**Issue by c10b10** [oblitum/rainbow#15]
Take a look at the first line:

![screenshot 2015-04-10 17 33 20](https://cloud.githubusercontent.com/assets/306633/7089920/00df2f5a-dfa8-11e4-9a6f-f0ada1520ee1.png)

**Comment by oblitum** [comment]
This is strange, but as can be checked at the README. This plugin is not supported anymore.

**Comment by c10b10** [comment]
Is there an alternative that you recommend?

**Comment by oblitum** [comment]
@c10b10 you may try luochen version, as I explain at the README, kien or junegunn unrelated implementation should also be fine I guess. If your problem reproduces in all of then, you should have some conflicting plugins or colorscheme:

https://github.com/junegunn/rainbow_parentheses.vim

**Comment by c10b10** [comment]
It seems that https://github.com/luochen1990/rainbow works great. Thanks.
